### ISSUE TITLE
Conformer vs. LSTM ?

### ISSUE THREAD

**Issue by hbredin** [BUTSpeechFIT/DiariZen#2]
Thanks a lot for sharing your code. That's really helpful for the community! 

I am [in the process](https://github.com/pyannote/pyannote-audio/pull/1776) of reproducing this work in `pyannote.audio` and was wondering whether you also compared to the [SSeRiouSS](https://github.com/pyannote/pyannote-audio/blob/a39991b92db46127ad3a3ec87cd0a933b18c8013/pyannote/audio/models/segmentation/SSeRiouSS.py#L45) architecture which basically uses LSTMs in place of Conformer (but still uses WavLM as input features).

For instance, this is what is done in Rev's latest [_Reverb Diarization V2_](https://github.com/revdotcom/reverb/tree/89b7d9153d487c3825636b2200f624a6b50df4af/diarization) model.

**Comment by jyhan03** [comment]
Hi Hervé, you’re welcome and thanks for your interest in our work.

Just let me know if you have any questions when reproducing our work. 
I can also run some experiments from my side for comparisons. 

We didn't use `SSeRiouSS`.

**Comment by hbredin** [comment]
Closing as I got my answer :)
