### ISSUE TITLE
Infer script

### ISSUE THREAD

**Issue by MonolithFoundation** [BUTSpeechFIT/DiariZen#3]
Hi, is there a infer script which takes an long audio in , and outputs the time period as well as speaker id?
Currently really hard to hands on this

**Comment by jyhan03** [comment]
Hi, we don't have such a script. Maybe you could find some useful functions/tutorials in the [Pyannote repo](https://github.com/pyannote/pyannote-audio), or write a post-processing script to deal with the generated RTTMs.
